language: node_js
node_js:
  - node
install:
- yarn global add travis-ci-cloudfront-invalidation
- yarn global add vuepress  
- yarn
script:
- yarn docs:build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  bucket: 'esper-dev-hub'
  local_dir: docs/.vuepress/dist
  skip_cleanup: true
  on:
    branch: develop
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
